lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/multiqc_config.yaml
    - assets/svrank_model.ini
    - .github/workflows/linting.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/branch.yml
repository_type: pipeline
